import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderTop from "./components/HeaderTop";
import HeaderMain from "./components/HeaderMain";
import Navbar from "./components/Navbar";
import MobNavbar from "./components/MobNavbar";
// react slick animations
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "./components/Footer";
import { Providers } from "./components/Providers";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense>
          <Providers>
            <main className="min-h-screen flex flex-col">
              <HeaderTop />
              <HeaderMain />
              <Navbar />
              <MobNavbar />
              <div className="flex-1">{children}</div>
              <Footer />
            </main>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
